{% set version = "1.21.1" %}

package:
  name: wget
  version: {{ version }}

source:
  url: http://ftp.gnu.org/gnu/wget/wget-{{ version }}.tar.gz
  sha256: 59ba0bdade9ad135eda581ae4e59a7a9f25e3a4bde6a5419632b31906120e26e

build:
  number: 0
  skip: True  # [win]
  # To fix a build error "run-exports library package pkgs/main::libunistring in requirements/run but it is not used"
  ignore_run_exports:
    - libunistring

requirements:
  build:
    - {{ compiler('c') }}
    - pkg-config
    - make
  host:
    - openssl
    - libidn2
    # When Wget 1.18+ is built with libiconv, it now converts non-ASCII URIs to
    # the locale's codeset when it creates files https://git.savannah.gnu.org/cgit/wget.git/tree/NEWS
    - libiconv  # [not ppc64le]
    - libunistring
    - zlib
  run:
    - openssl
    - libidn2
    - libiconv  # [not ppc64le]
    - libunistring
    - zlib

test:
  commands:
    - wget --help
    - wget --version
      # test that SSL works
    - wget https://github.com/conda-forge

about:
  home: https://www.gnu.org/software/wget/
  license: GPL-3.0
  license_family: GPL
  license_file: COPYING
  summary: utility for non-interactive download of files from the Web
  description: |
    wget is a free software package for retrieving files using HTTP, HTTPS and FTP,
    the most widely-used Internet protocols.
  doc_url: https://www.gnu.org/software/wget/
  doc_source_url: https://savannah.gnu.org/projects/wget/
  dev_url: https://git.savannah.gnu.org/cgit/wget.git/tree/

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening

# This recipe was derived from the wget recipe in the defaults channel.
