{% set version = "1.24.5" %}

package:
  name: wget
  version: {{ version }}

source:
  url: https://ftp.gnu.org/gnu/wget/wget-{{ version }}.tar.gz
  sha256: fa2dc35bab5184ecbc46a9ef83def2aaaa3f4c9f3c97d4bd19dcb07d4da637de

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - pkg-config
    - make
  host:
    - openssl {{ openssl }}
    - libidn2 2.3.4
    - zlib 1.2.13
    - libunistring 0.9.10
  run:
    - openssl  # exact pin handled through openssl run_exports
    - libidn2
    - zlib
    - libunistring

test:
  commands:
    - wget --help
    - wget --version
      # test that SSL works
    - wget https://github.com/conda-forge

about:
  home: https://www.gnu.org/software/wget/
  license: GPL-3.0-or-later
  license_file: COPYING
  license_family: GPL
  summary: utility for non-interactive download of files from the Web
  description: |
    wget is a free software package for retrieving files using HTTP, HTTPS and FTP,
    the most widely-used Internet protocols.
  doc_url: https://www.gnu.org/software/wget/
  dev_url: https://savannah.gnu.org/git/?group=wget

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening

# This recipe was derived from the wget recipe in the defaults channel.
