{% set version = "2.2.0" %}

package:
  name: wget
  version: {{ version }}

source:
  url: https://ftp.gnu.org/gnu/wget/wget2-{{ version }}.tar.gz
  sha256: 2b3b9c85b7fb26d33ca5f41f1f8daca71838d869a19b406063aa5c655294d357
  
build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - pkg-config
    - make
    - flex
  host:
    - openssl {{ openssl }}
    - libidn2 2.3.4
    - zlib 1.2.13
    - libunistring 0.9.10
    - pcre 8.45
  run:
    - openssl  # exact pin handled through openssl run_exports
    - libidn2
    - zlib
    - libiconv
    - libunistring
    - pandoc
    - gettext >=0.18.2

test:
  commands:
    - wget --help
    - wget --version
      # test that SSL works
    - wget https://github.com/conda-forge

about:
  home: https://www.gnu.org/software/wget/
  license: GPL-3.0-or-later
  license_file: COPYING
  license_family: GPL
  summary: utility for non-interactive download of files from the Web
  description: |
    wget is a free software package for retrieving files using HTTP, HTTPS and FTP,
    the most widely-used Internet protocols.
  doc_url: https://www.gnu.org/software/wget/
  dev_url: https://savannah.gnu.org/git/?group=wget

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening

# This recipe was derived from the wget recipe in the defaults channel.
