{% set name = "wget" %}
{% set version = "1.25.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  # Using mirror server since the default one is unreachable by CI
  url: https://ftpmirror.gnu.org/gnu/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 766e48423e79359ea31e41db9e5c289675947a7fcf2efdcedb726ac9d0da3784

build:
  number: 2
  skip: True  # [win]

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - pkg-config
    - make
  host:
    - openssl {{ openssl }}
    - libidn2 {{ libidn2 }}
    - zlib {{ zlib }}
    - pcre2 {{ pcre2 }}
    - gettext {{ gettext }}
    - libiconv {{ libiconv }}
    - libunistring 1.3
  run:
    - openssl  # exact pin handled through openssl run_exports
    - libidn2
    - zlib
    - libunistring
    - pcre2

test:
  commands:
    - wget --help
    - wget --version
      # test that SSL works
    - wget https://github.com/conda-forge

about:
  home: https://www.gnu.org/software/wget
  license: GPL-3.0-or-later
  license_file: COPYING
  license_family: GPL
  summary: utility for non-interactive download of files from the Web
  description: |
    wget is a free software package for retrieving files using HTTP, HTTPS and FTP,
    the most widely-used Internet protocols.
  doc_url: https://www.gnu.org/software/wget
  dev_url: https://savannah.gnu.org/git/?group=wget

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening

# This recipe was derived from the wget recipe in the defaults channel.