travis:
  secure:
    BINSTAR_TOKEN: c/muof+oZ+jfkGeB9t7kbPpqCcxM1hAHuh1SKwSxlhI3/ZM0zCXB/v26n3G659n+/4mJZU+X9ka6XQDVhKnUdRMdl2uNiFUE1S0wKPRy0HmzvHgwA8mBuobJo0CwoaKt2LCJL83bphERqfIHiY6GgP5WKIhQxZ1D/qmlJRnwXK4gyqf1Aj8QTB3aIWraU7bHH28H23O902ojYEBSF/5Inuks3xU8kk3+WCEVq9lvVwRG48eDOirU2gJ/PSGApTbZO6fQsdFQxbfpGSA9WGeUGZZCmolBcVl+/LBY6ccOg122EIHiHS68jWZLZpXP1tVYKWgC/ybQf+T0dinWuy5u9NSNE37Tu45YvznqPfyVK0u3GbBdjffyN5W4nRiS2BySnH7/xXDE+xOvSVTdIpgjV6wRKsWhy3CPF1MiKqO79MkOvWCtGv7tJ2vVHvh/HWsvDIlHFuzW/y2TwJvQHMriMiGDW78HdTVPzFpN4XZM4Z3MonzaPZipITV7cJjsmOxQJlLMFSjkZQjIbnjBEwBluMBOlsGG/igcfsSNnW9LmO4h8SZvW0oKCH6WN+qc6Zq2DS1DYzAgoN16/KQ35rTze0SdyxlvmSAsF9grthZR/rhySeTJLyUTegyZuVOqcI7G62OyVS0SLfxGrLV8dmyj0jMG1dR7BfuS/+gcqNJ10q0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
