travis:
  secure:
    BINSTAR_TOKEN: U4K3QLF+S7U35F7z9nx8zADkKzqeekTP8mN2/LZ5MZdKvFEatYfSVEvgEyIHaF7pOoQZPTl9Wqo8KzzjAa06c6fldKOt7bqeNiQba43K8nuK5d15oDFIOcZs24X8XWpf4t5ft2dXWZ1fK3dXjTYV8hBrHEdAFx1Vgfqbsozhg5SZvCXclTBMG8icHbFUig4VlL/84ss/cDw7QMRIbsLAX7GW3+O56ER5npEIfLBrNxUl9yyRQppJkDkP0jJDXohY14GNzwlOoGxAyRLem4aJcarwcRYUBq2fC81Yzh+LuCU0uTin/ClIBk4d5ClkeH9rOfmARN2P1CjoJPK8MQlOkXrN8ZyAP6VW7WLL0oJdLWeC3lV5NnSdEy+sKAAp9QtIQ9JTCDSy0IwfxHFqJvTOz2+0l6qhTmL5SeaUltnmwDTfgyxyz53KliynOkQxqO2+cjo8b7p/6GvlvrGIlijnxQfVnSbVLprbECauCJ/5i5R4QYu9kblYoRJ4mmftFQ9dY+ZfZtn4tgA+01VbhkI8HAWKpE7Y0zaHeN8/4IfgFd+LqFvWHFGGw7guW8VAUB56FBIQ+U2eUOiNKdupffCvZMbAcCaKi0jRcQRiAy88M69sV8wWFHZt7hGvtVmJUErU1cXu2gfuo6XwlD4AI7HWfin3QHrj0aD/tpaJMY0YQZg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
